//p_c.js
module.exports = {
	"province": [{
		"title": "北京",
		"weight": 20,
		"evaluation_value": 0,
		"code": "bj",
		"disabled": false
	}, {
		"title": "上海",
		"weight": 1,
		"evaluation_value": 0,
		"hint": "",
		"code": "sh",
		"disabled": false
	}, {
		"title": "天津",
		"weight": 300,
		"evaluation_value": 0,
		"code": "tj",
		"disabled": false
	}, {
		"title": "重庆",
		"weight": 30,
		"evaluation_value": 0,
		"code": "cq",
		"disabled": false
	}, {
		"title": "江苏",
		"weight": 3,
		"evaluation_value": 0,
		"hint": "",
		"code": "js",
		"disabled": false
	}, {
		"title": "浙江",
		"weight": 5,
		"evaluation_value": 0,
		"hint": "",
		"code": "zj",
		"disabled": false
	}, {
		"title": "安徽",
		"weight": 10,
		"evaluation_value": 0,
		"code": "ah",
		"disabled": false
	}, {
		"title": "福建",
		"weight": 40,
		"evaluation_value": 0,
		"code": "fj",
		"disabled": false
	}, {
		"title": "甘肃",
		"weight": 50,
		"evaluation_value": 0,
		"code": "gs",
		"disabled": false
	}, {
		"title": "广东",
		"weight": 60,
		"evaluation_value": 0,
		"code": "gd",
		"disabled": false
	}, {
		"title": "广西",
		"weight": 70,
		"evaluation_value": 0,
		"code": "gx",
		"disabled": false
	}, {
		"title": "贵州",
		"weight": 80,
		"evaluation_value": 0,
		"code": "gz",
		"disabled": false
	}, {
		"title": "海南",
		"weight": 90,
		"evaluation_value": 0,
		"code": "hn1",
		"disabled": false
	}, {
		"title": "河北",
		"weight": 100,
		"evaluation_value": 0,
		"code": "hb1",
		"disabled": false
	}, {
		"title": "黑龙江",
		"weight": 110,
		"evaluation_value": 0,
		"code": "hlj",
		"disabled": false
	}, {
		"title": "河南",
		"weight": 120,
		"evaluation_value": 0,
		"code": "hn2",
		"disabled": false
	}, {
		"title": "香港",
		"weight": 130,
		"evaluation_value": 0,
		"code": "xg",
		"disabled": false
	}, {
		"title": "湖北",
		"weight": 140,
		"evaluation_value": 0,
		"code": "hb2",
		"disabled": false
	}, {
		"title": "湖南",
		"weight": 150,
		"evaluation_value": 0,
		"code": "hn3",
		"disabled": false
	}, {
		"title": "江西",
		"weight": 170,
		"evaluation_value": 0,
		"code": "jx",
		"disabled": false
	}, {
		"title": "吉林",
		"weight": 180,
		"evaluation_value": 0,
		"code": "jl",
		"disabled": false
	}, {
		"title": "辽宁",
		"weight": 190,
		"evaluation_value": 0,
		"code": "ln",
		"disabled": false
	}, {
		"title": "澳门",
		"weight": 200,
		"evaluation_value": 0,
		"code": "am",
		"disabled": false
	}, {
		"title": "内蒙古",
		"weight": 210,
		"evaluation_value": 0,
		"code": "nmg",
		"disabled": false
	}, {
		"title": "宁夏",
		"weight": 220,
		"evaluation_value": 0,
		"code": "nx",
		"disabled": false
	}, {
		"title": "青海",
		"weight": 230,
		"evaluation_value": 0,
		"code": "qh",
		"disabled": false
	}, {
		"title": "山东",
		"weight": 240,
		"evaluation_value": 0,
		"code": "sd",
		"disabled": false
	}, {
		"title": "陕西",
		"weight": 260,
		"evaluation_value": 0,
		"code": "sx1",
		"disabled": false
	}, {
		"title": "山西",
		"weight": 270,
		"evaluation_value": 0,
		"code": "sx2",
		"disabled": false
	}, {
		"title": "四川",
		"weight": 280,
		"evaluation_value": 0,
		"code": "sc",
		"disabled": false
	}, {
		"title": "台湾",
		"weight": 290,
		"evaluation_value": 0,
		"code": "tw",
		"disabled": false
	}, {
		"title": "新疆",
		"weight": 310,
		"evaluation_value": 0,
		"code": "xj",
		"disabled": false
	}, {
		"title": "西藏",
		"weight": 320,
		"evaluation_value": 0,
		"code": "xz",
		"disabled": false
	}, {
		"title": "云南",
		"weight": 330,
		"evaluation_value": 0,
		"code": "yn",
		"disabled": false
	}],
	"city": [{
		"title": "合肥",
		"weight": 10,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "黄山",
		"weight": 20,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "安庆",
		"weight": 30,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "芜湖",
		"weight": 40,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "蚌埠",
		"weight": 50,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "淮北",
		"weight": 60,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "六安",
		"weight": 70,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "阜阳",
		"weight": 80,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "宿州",
		"weight": 90,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "巢湖",
		"weight": 100,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "马鞍山",
		"weight": 110,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "淮南",
		"weight": 120,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "滁州",
		"weight": 130,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "池州",
		"weight": 140,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "铜陵",
		"weight": 150,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "亳州",
		"weight": 160,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ah"
	}, {
		"title": "北京",
		"weight": 180,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "bj"
	}, {
		"title": "重庆",
		"weight": 370,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "cq"
	}, {
		"title": "福州",
		"weight": 780,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "厦门",
		"weight": 790,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "泉州",
		"weight": 800,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "漳州",
		"weight": 810,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "莆田",
		"weight": 820,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "宁德",
		"weight": 830,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "南平",
		"weight": 840,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "三明",
		"weight": 850,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "龙岩",
		"weight": 860,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "fj"
	}, {
		"title": "兰州",
		"weight": 880,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "天水",
		"weight": 890,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "武威",
		"weight": 900,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "酒泉",
		"weight": 910,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "张掖",
		"weight": 920,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "定西",
		"weight": 930,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "嘉峪关",
		"weight": 940,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "平凉",
		"weight": 950,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "庆阳",
		"weight": 960,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "白银",
		"weight": 970,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "陇南",
		"weight": 980,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "金昌",
		"weight": 990,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "临夏",
		"weight": 1000,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "甘南",
		"weight": 1010,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gs"
	}, {
		"title": "深圳",
		"weight": 1030,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "广州",
		"weight": 1040,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "东莞",
		"weight": 1050,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "惠州",
		"weight": 1060,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "佛山",
		"weight": 1070,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "汕头",
		"weight": 1080,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "中山",
		"weight": 1090,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "珠海",
		"weight": 1100,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "湛江",
		"weight": 1110,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "江门",
		"weight": 1120,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "河源",
		"weight": 1130,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "潮州",
		"weight": 1140,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "梅州",
		"weight": 1150,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "揭阳",
		"weight": 1160,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "茂名",
		"weight": 1170,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "肇庆",
		"weight": 1180,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "韶关",
		"weight": 1190,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "清远",
		"weight": 1200,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "汕尾",
		"weight": 1210,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "云浮",
		"weight": 1220,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "阳江",
		"weight": 1230,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gd"
	}, {
		"title": "南宁",
		"weight": 1250,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "桂林",
		"weight": 1260,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "柳州",
		"weight": 1270,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "玉林",
		"weight": 1280,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "贵港",
		"weight": 1290,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "梧州",
		"weight": 1300,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "北海",
		"weight": 1310,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "百色",
		"weight": 1320,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "河池",
		"weight": 1330,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "钦州",
		"weight": 1340,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "防城港",
		"weight": 1350,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "来宾",
		"weight": 1360,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "崇左",
		"weight": 1370,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "贺州",
		"weight": 1380,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gx"
	}, {
		"title": "贵阳",
		"weight": 1400,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "遵义",
		"weight": 1410,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "黔东南",
		"weight": 1420,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "安顺",
		"weight": 1430,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "黔南",
		"weight": 1440,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "毕节",
		"weight": 1450,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "六盘水",
		"weight": 1460,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "铜仁",
		"weight": 1470,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "黔西南",
		"weight": 1480,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "gz"
	}, {
		"title": "三亚",
		"weight": 1500,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn1"
	}, {
		"title": "海口",
		"weight": 1510,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn1"
	}, {
		"title": "石家庄",
		"weight": 1530,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "保定",
		"weight": 1540,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "唐山",
		"weight": 1550,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "沧州",
		"weight": 1560,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "邯郸",
		"weight": 1570,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "廊坊",
		"weight": 1580,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "邢台",
		"weight": 1590,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "衡水",
		"weight": 1600,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "秦皇岛",
		"weight": 1610,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "张家口",
		"weight": 1620,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "承德",
		"weight": 1630,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb1"
	}, {
		"title": "哈尔滨",
		"weight": 1650,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "齐齐哈尔",
		"weight": 1660,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "大庆",
		"weight": 1670,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "牡丹江",
		"weight": 1680,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "佳木斯",
		"weight": 1690,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "鸡西",
		"weight": 1700,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "黑河",
		"weight": 1710,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "绥化",
		"weight": 1720,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "双鸭山",
		"weight": 1730,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "伊春",
		"weight": 1740,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "鹤岗",
		"weight": 1750,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "大兴安岭",
		"weight": 1760,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "七台河",
		"weight": 1770,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hlj"
	}, {
		"title": "郑州",
		"weight": 1790,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "南阳",
		"weight": 1800,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "新乡",
		"weight": 1810,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "洛阳",
		"weight": 1820,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "安阳",
		"weight": 1830,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "开封",
		"weight": 1840,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "信阳",
		"weight": 1850,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "焦作",
		"weight": 1860,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "平顶山",
		"weight": 1870,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "周口",
		"weight": 1880,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "三门峡",
		"weight": 1890,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "商丘",
		"weight": 1900,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "驻马店",
		"weight": 1910,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "许昌",
		"weight": 1920,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "濮阳",
		"weight": 1930,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "漯河",
		"weight": 1940,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "鹤壁",
		"weight": 1950,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "济源",
		"weight": 1960,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn2"
	}, {
		"title": "香港",
		"weight": 1980,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xg"
	}, {
		"title": "武汉",
		"weight": 1990,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "宜昌",
		"weight": 2000,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "十堰",
		"weight": 2010,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "孝感",
		"weight": 2020,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "荆州",
		"weight": 2030,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "襄樊",
		"weight": 2040,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "黄冈",
		"weight": 2050,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "黄石",
		"weight": 2060,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "恩施",
		"weight": 2070,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "随州",
		"weight": 2080,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "荆门",
		"weight": 2090,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "天门",
		"weight": 2100,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "仙桃",
		"weight": 2110,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "咸宁",
		"weight": 2120,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "潜江",
		"weight": 2130,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "神农架林区",
		"weight": 2140,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "鄂州",
		"weight": 2150,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hb2"
	}, {
		"title": "长沙",
		"weight": 2170,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "常德",
		"weight": 2180,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "湘潭",
		"weight": 2190,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "衡阳",
		"weight": 2200,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "岳阳",
		"weight": 2210,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "怀化",
		"weight": 2220,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "邵阳",
		"weight": 2230,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "株洲",
		"weight": 2240,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "益阳",
		"weight": 2250,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "娄底",
		"weight": 2260,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "郴州",
		"weight": 2270,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "永州",
		"weight": 2280,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "张家界",
		"weight": 2290,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "湘西",
		"weight": 2300,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "hn3"
	}, {
		"title": "南京",
		"weight": 2320,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "苏州",
		"weight": 2330,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "徐州",
		"weight": 2340,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "无锡",
		"weight": 2350,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "南通",
		"weight": 2360,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "连云港",
		"weight": 2370,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "扬州",
		"weight": 2380,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "淮安",
		"weight": 2390,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "盐城",
		"weight": 2400,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "常州",
		"weight": 2410,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "镇江",
		"weight": 2420,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "泰州",
		"weight": 2430,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "宿迁",
		"weight": 2440,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "js"
	}, {
		"title": "南昌",
		"weight": 2460,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "赣州",
		"weight": 2470,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "九江",
		"weight": 2480,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "上饶",
		"weight": 2490,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "吉安",
		"weight": 2500,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "景德镇",
		"weight": 2510,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "宜春",
		"weight": 2520,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "抚州",
		"weight": 2530,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "萍乡",
		"weight": 2540,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "新余",
		"weight": 2550,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "鹰潭",
		"weight": 2560,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jx"
	}, {
		"title": "长春",
		"weight": 2580,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "吉林",
		"weight": 2590,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "白城",
		"weight": 2600,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "延边",
		"weight": 2610,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "白山",
		"weight": 2620,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "四平",
		"weight": 2630,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "松原",
		"weight": 2640,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "通化",
		"weight": 2650,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "辽源",
		"weight": 2660,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "jl"
	}, {
		"title": "沈阳",
		"weight": 2680,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "大连",
		"weight": 2690,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "丹东",
		"weight": 2700,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "葫芦岛",
		"weight": 2710,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "辽阳",
		"weight": 2720,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "锦州",
		"weight": 2730,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "鞍山",
		"weight": 2740,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "盘锦",
		"weight": 2750,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "抚顺",
		"weight": 2760,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "朝阳",
		"weight": 2770,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "营口",
		"weight": 2780,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "铁岭",
		"weight": 2790,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "本溪",
		"weight": 2800,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "阜新",
		"weight": 2810,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "ln"
	}, {
		"title": "澳门",
		"weight": 2830,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "am"
	}, {
		"title": "呼和浩特",
		"weight": 2840,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "包头",
		"weight": 2850,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "赤峰",
		"weight": 2860,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "呼伦贝尔",
		"weight": 2870,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "通辽",
		"weight": 2880,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "乌海",
		"weight": 2890,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "鄂尔多斯",
		"weight": 2900,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "乌兰察布",
		"weight": 2910,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "锡林郭勒盟",
		"weight": 2920,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "兴安盟",
		"weight": 2930,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "巴彦淖尔",
		"weight": 2940,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "阿拉善盟",
		"weight": 2950,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nmg"
	}, {
		"title": "银川",
		"weight": 2970,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nx"
	}, {
		"title": "石嘴山",
		"weight": 2980,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nx"
	}, {
		"title": "吴忠",
		"weight": 2990,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nx"
	}, {
		"title": "固原",
		"weight": 3000,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nx"
	}, {
		"title": "中卫",
		"weight": 3010,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "nx"
	}, {
		"title": "西宁",
		"weight": 3030,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "海西",
		"weight": 3040,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "海东",
		"weight": 3050,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "海南",
		"weight": 3060,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "海北",
		"weight": 3070,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "玉树",
		"weight": 3080,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "黄南",
		"weight": 3090,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "果洛",
		"weight": 3100,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "qh"
	}, {
		"title": "青岛",
		"weight": 3120,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "济南",
		"weight": 3130,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "潍坊",
		"weight": 3140,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "淄博",
		"weight": 3150,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "烟台",
		"weight": 3160,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "临沂",
		"weight": 3170,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "泰安",
		"weight": 3180,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "济宁",
		"weight": 3190,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "威海",
		"weight": 3200,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "东营",
		"weight": 3210,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "菏泽",
		"weight": 3220,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "日照",
		"weight": 3230,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "滨州",
		"weight": 3240,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "聊城",
		"weight": 3250,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "德州",
		"weight": 3260,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "枣庄",
		"weight": 3270,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "莱芜",
		"weight": 3280,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sd"
	}, {
		"title": "上海",
		"weight": 3300,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sh"
	}, {
		"title": "西安",
		"weight": 3480,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "咸阳",
		"weight": 3490,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "宝鸡",
		"weight": 3500,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "渭南",
		"weight": 3510,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "汉中",
		"weight": 3520,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "安康",
		"weight": 3530,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "榆林",
		"weight": 3540,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "延安",
		"weight": 3550,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "铜川",
		"weight": 3560,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "商洛",
		"weight": 3570,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx1"
	}, {
		"title": "太原",
		"weight": 3590,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "长治",
		"weight": 3600,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "大同",
		"weight": 3610,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "晋城",
		"weight": 3620,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "运城",
		"weight": 3630,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "晋中",
		"weight": 3640,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "忻州",
		"weight": 3650,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "临汾",
		"weight": 3660,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "阳泉",
		"weight": 3670,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "吕梁",
		"weight": 3680,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "朔州",
		"weight": 3690,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sx2"
	}, {
		"title": "成都",
		"weight": 3710,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "乐山",
		"weight": 3720,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "绵阳",
		"weight": 3730,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "广元",
		"weight": 3740,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "南充",
		"weight": 3750,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "达州",
		"weight": 3760,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "德阳",
		"weight": 3770,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "攀枝花",
		"weight": 3780,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "内江",
		"weight": 3790,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "宜宾",
		"weight": 3800,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "雅安",
		"weight": 3810,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "凉山",
		"weight": 3820,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "遂宁",
		"weight": 3830,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "眉山",
		"weight": 3840,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "泸州",
		"weight": 3850,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "巴中",
		"weight": 3860,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "自贡",
		"weight": 3870,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "资阳",
		"weight": 3880,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "阿坝",
		"weight": 3890,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "广安",
		"weight": 3900,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "甘孜",
		"weight": 3910,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "sc"
	}, {
		"title": "天津",
		"weight": 3930,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "tj"
	}, {
		"title": "台湾",
		"weight": 4120,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "tw"
	}, {
		"title": "乌鲁木齐",
		"weight": 4130,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "石河子",
		"weight": 4140,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "伊犁",
		"weight": 4150,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "哈密",
		"weight": 4160,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "巴音郭楞",
		"weight": 4170,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "昌吉",
		"weight": 4180,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "阿勒泰",
		"weight": 4190,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "喀什",
		"weight": 4200,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "塔城",
		"weight": 4210,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "阿克苏",
		"weight": 4220,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "克拉玛依",
		"weight": 4230,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "吐鲁番",
		"weight": 4240,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "和田",
		"weight": 4250,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "博尔塔拉",
		"weight": 4260,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "五家渠",
		"weight": 4270,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "阿拉尔",
		"weight": 4280,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "克孜勒苏",
		"weight": 4290,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "图木舒克",
		"weight": 4300,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xj"
	}, {
		"title": "拉萨",
		"weight": 4320,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "日喀则",
		"weight": 4330,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "林芝",
		"weight": 4340,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "阿里",
		"weight": 4350,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "那曲",
		"weight": 4360,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "昌都",
		"weight": 4370,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "山南",
		"weight": 4380,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "xz"
	}, {
		"title": "昆明",
		"weight": 4400,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "丽江",
		"weight": 4410,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "曲靖",
		"weight": 4420,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "玉溪",
		"weight": 4430,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "昭通",
		"weight": 4440,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "大理",
		"weight": 4450,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "楚雄",
		"weight": 4460,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "临沧",
		"weight": 4470,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "红河",
		"weight": 4480,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "保山",
		"weight": 4490,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "普洱",
		"weight": 4500,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "西双版纳",
		"weight": 4510,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "德宏",
		"weight": 4520,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "文山",
		"weight": 4530,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "迪庆",
		"weight": 4540,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "怒江",
		"weight": 4550,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "yn"
	}, {
		"title": "杭州",
		"weight": 4570,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "温州",
		"weight": 4580,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "宁波",
		"weight": 4590,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "台州",
		"weight": 4600,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "金华",
		"weight": 4610,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "绍兴",
		"weight": 4620,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "嘉兴",
		"weight": 4630,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "湖州",
		"weight": 4640,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "丽水",
		"weight": 4650,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "衢州",
		"weight": 4660,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}, {
		"title": "舟山",
		"weight": 4670,
		"evaluation_value": 0,
		"disabled": false,
		"parent_code": "zj"
	}]
}
